Add <limits> headers for gcc-12
gcc-12 cleaned up headers dependencies a bit and exposed
missing header inclusion:

    src/c++/lib/calibration/IndelErrorModel.hh:100:33: error: 'numeric_limits' is not a member of 'std'
      100 |     double logErrorRate = -std::numeric_limits<double>::infinity();
          |                                 ^~~~~~~~~~~~~~